### ISSUE TITLE
User agent doesn't meet Reddit's API Requirements

### ISSUE THREAD

**Issue by Xalaxis** [LucasAnderson07/RedditSubMatch#6]
Reddit requires it's API to meet [a set of rules](https://github.com/reddit-archive/reddit/wiki/API).  Currently the project doesn't meet the user agent rules.

> Change your client's User-Agent string to something unique and descriptive, including the target platform, a unique application identifier, a version string, and your username as contact information, in the following format:
> \<platform>:\<app ID>:\<version string> (by /u/\<reddit username>)
> Example: User-Agent: android:com.example.myredditapp:v1.2.3 (by /u/kemitche)

Please can we update the [main.py](https://github.com/LucasAnderson07/RedditSubMatch/blob/80b7f8b33e793398f595dc14d092654d2783131b/main.py#L7) to meet these requirements?

I would put in a pull-request, but I don't know what the username is of the API key owner 🙂 .

**Comment by EarlyHemisphere** [comment]
main.py was actually a file left over from before project development was launched and currently is unused. It's been deleted now. The user agents used in match.py follow the standards.
